name: Test proposed changes

on: 
  push:
    branches:
      - '**'
      - '!main'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest action code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Build
        run: |
          sed -i "s/0.0.0-development/${{ vars.MAJOR }}.${{ vars.MINOR }}/" package.json
          sed -i "s/0.0.0-development/${{ vars.MAJOR }}.${{ vars.MINOR }}/" package-lock.json   
          #rm -f package-lock.json
          npm i -g @vercel/ncc
          npm install --omit=dev
          npm run build
          #npm run build_stats
          #npm exec --yes -- webpack-bundle-analyzer dist/stats dist -O -m static

      - name: Clean files
        run: |
          rm .gitignore
          rm -f renovate.json
          rm -Rf node_modules/
          rm -Rf .github
          rm index.js
          rm -f dist/stats
          rm -f dist/index.js.map
          rm -f dist/index.873.js.map
          rm -f dist/sourcemap-register.js

      - name: Test action
        uses: ./
        with:
          name: 'TEST'
          value: 'abcd123'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Test encrypted secret
        run: |
          echo ${{ secrets.TEST }}
          echo 'abcd123'
          echo 'There should be two lines of asterisks above this if the secret was added successfully.'

